blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
]

crmsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from crm import views


urlpatterns = [
    path('', views.home, name='home'),
    path('auth/', include('personal_account_admin.urls')),
    path('news/', include('news.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news, name='news'),
]

personal_account_admin/urls.py
from django.urls import path
from . import views

app_name = 'personal_account_admin'

urlpatterns = [
    path('', views.auth, name='auth'),
]

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    date = models.DateField()

crm/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

news/models.py
from django.db import models

# Create your models here.

personal_account_admin/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from .models import Blog

def blog(request):
    blog = Blog.objects.all()
    return render(request, 'blog/all_blog.html',{'blog':blog})

crm/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'crm/home.html', {'projects':projects})

news/views.py
from django.shortcuts import render

def news(request):
    return render(request, 'news/news.html')

personal_account_admin/views.py
from django.shortcuts import render

def auth(request):
    return render(request, 'personal_account_admin/auth.html')

blog/templates/blog/all_blog.html
<h1>Блог учеников</h1>
<a class="navbar-brand" href="{% url 'home' %}">
    <span>Назад на главную</span>
</a>

{% for data in blog %}

<h2>{{ data.title }}</h2>
<h3>{{ data.description }}</h3>
<a>{{ data.date|date:'M d Y'|upper }}</a>

{% endfor %}

crm/templates/crm/home.html
<a class="navbar-brand" href="{% url 'news:news' %}">
    <span>Новости</span>
</a>
<br>
<a class="navbar-brand" href="{% url 'personal_account_admin:auth' %}">
    <span>ЛК администратора</span>
</a>
<br>
<a class="navbar-brand" href="{% url 'blog:blog' %}">
    <span>Блог</span>
</a>
<br>

<h1>CRM система для Образовательных Учреждений</h1>

{% for project in projects %}

<h2>{{ project.title }}</h2>

<img src="{{project.image.url}}">

{% endfor %}

news/templates/news/news.html
<h1>Новости Образовательного Учреждения</h1>
<a class="navbar-brand" href="{% url 'home' %}">
    <span>Назад на главную</span>
</a>

personal_account_admin/templates/personal_account_admin/auth.html
<h1>ЛК администратора CRM</h1>
<a class="navbar-brand" href="{% url 'home' %}">
    <span>Назад на главную</span>
</a>